version: "3.9"
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: simple_bank
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_SOURCE: "postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
  